export enum NavigationTarget {
    TRON_ACCOUNT_MANARGER = "TRON_ACCOUNT_MANARGER",
    TRANSFER_RECORDS_MANARGER = "TRANSFER_RECORDS_MANARGER",
    DEPOSIT_ORDER_MANARGER = "DEPOSIT_ORDER_MANARGER",
    RENTAL_ORDER_MANARGER = "RENTAL_ORDER_MANARGER",
    SETTING = "SETTING"
  }
  