import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "./store";
import TronAccountViewModelProvider from "./tronaccountviewmodel";
import TransferViewModelProvider from "./transferviewmodel";
import DepositOrderViewModelProvider from "./depositorderviewmodel";
import RentalOrderViewModelProvider from "./rentalorderviewmodel";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Lightning Control Center",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="zh">
      <body className={inter.className} theme-mode="dark">
        <StoreProvider>
          <TronAccountViewModelProvider>
            <TransferViewModelProvider>
              <DepositOrderViewModelProvider>
                <RentalOrderViewModelProvider>
                {children}
                </RentalOrderViewModelProvider>
                
              </DepositOrderViewModelProvider>
            </TransferViewModelProvider>
          </TronAccountViewModelProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
